name: CI

on:
  schedule:
    - cron: 10 * * * *

jobs:
  build:

    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Check Build Tools
      run: |
        devenv /?
        MSBuild -help
