name: CI

on:
  push:

jobs:
  build:

    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Check Build Tools
      run: |
        call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvarsall.bat" x64
        MSBuild "%GITHUB_WORKSPACE%\codecvt.sln" -nologo -p:Configuration=Release -t:build
    - uses: actions/upload-artifact@master
      with:
        name: codecvt
        path: "%GITHUB_WORKSPACE%\\x64\\Release\\codecvt.exe"
